module:
  block: 0
  breakpoint: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  lunr: 0
  node: 0
  page_cache: 0
  serialization: 0
  system: 0
  text: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_sync: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
  views_ui: 0
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
